stages:
  atomgpt:
    cmd: bash scripts/run_atomgpt_data.sh
    deps:
      - scripts/run_atomgpt_data.sh
      - scripts/data_preprocess.py
    outs:
      - atomgpt_data
  cdvae:
    cmd: bash scripts/run_cdvae_data.sh
    deps:
      - scripts/run_cdvae_data.sh
      - scripts/data_preprocess.py
    outs:
      - ../models/cdvae/data/supercon:
          cache: false
  flowmm:
    cmd: bash scripts/run_flowmm_data.sh
    deps:
      - scripts/run_flowmm_data.sh
      - scripts/data_preprocess.py
    outs:
      - ../models/flowmm/data/supercon:
          cache: false
  check:
    cmd: python scripts/checker.py --atomgpt-dir ./atomgpt_data --cdvae-dir ../models/cdvae/data/supercon --flowmm-dir ../models/flowmm/data/supercon --strict-order
    deps:
      - scripts/checker.py

  charts:
    cmd: python scripts/histogram_pie_chart.py --output . --dataset dft_3d
    deps:
      - scripts/histogram_pie_chart.py
